name: First Pipeline Try

on:
  push:

jobs:
  first-ci:
    runs-on:
      - ubuntu-latest
    if: github.ref == 'refs/head/test'  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello CI/CD
        run: echo "Hello I'm learning CI/CD"
      - name: Goodbye CI/CD
        run: echo "Bye Bye"
      - name: Test Run
        run: echo "Tests are running."
      - name: List files
        run: ls    
    

